
spring:
  datasource:
    username: root
    password: mht
    url: jdbc:mysql://172.24.138.64:3306/we_manage?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      max-active: 20
#      min-idle: 5
#      max-wait: 60000
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#      time-between-eviction-runs-millis: 60000
#      max-evictable-idle-time-millis: 300000
#      min-evictable-idle-time-millis: 60000
#      validation-query: SELECT 1 FROM
#      validation-query-timeout: 60000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      filters: stat,log4j2,slf4j
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.manage.core.po

logging:
  level:
    com:
      example:
        mapper: debug
